# Target description
SOURCE_DIRS = src/client src/client/ministl

SOURCES := $(notdir $(wildcard $(addsuffix /*.cpp,$(SOURCE_DIRS))))
TARGET := management-bot
INCLUDEPATH = src/client src/client/ministl

vpath %.cpp $(SOURCE_DIRS)
vpath %.h $(SOURCE_DIRS)

USE_GCC := 1

# Default config
include makefiles/config.mk

DEFINES += _POSIX_C_SOURCE=201011

ifeq ($(USE_STL),1)
DEFINES += USE_STL
endif


# Default rules
include makefiles/rules.mk
