# Target description
SOURCES = list.c main.c debug.c
INCLUDEPATH = ../../src
TARGET = list-test

vpath %.c ../../src
vpath %.h ../../src

# Default config
include ../../makefiles/config.mk

DEFINES += USE_LIST_TYPEINFO USE_TERMINAL_COLORS

# Default rules
include ../../makefiles/rules.mk
